apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: lra-coordinator
    template: lra-coordinator
  name: lra-coordinator
spec:
  lookupPolicy:
    local: true
  tags:
  - from:
      kind: DockerImage
      name: docker.io/jbosstm/lra-coordinator:latest
    generation: 0
    importPolicy: {}
    name: "latest"
    referencePolicy:
      type: Source