apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: lra-coordinator
    template: lra-coordinator
  name: lra-coordinator
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi